@extends('admin.layouts.app')

@section('title', 'Добавить категорию блога')

@section('content')
<div class="p-6 space-y-6">
    <div class="flex justify-between items-center">
        <h2 class="text-2xl font-bold text-gray-900 dark:text-white">Добавить категорию блога</h2>
        <a href="{{ route('admin.blog.categories.index') }}" class="btn-secondary-admin">
            Назад к списку
        </a>
    </div>

    <div class="card-admin">
        <div class="p-6">
            <form action="{{ route('admin.blog.categories.store') }}" method="POST">
                @csrf
                <div class="grid grid-cols-1 gap-6">
                    <div>
                        <label for="name" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Название</label>
                        <input type="text" name="name" id="name" class="form-input-admin @error('name') border-red-500 @enderror" value="{{ old('name') }}" required>
                        @error('name')
                            <p class="text-red-500 text-xs mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    <div>
                        <label for="slug" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Slug (URL)</label>
                        <input type="text" name="slug" id="slug" class="form-input-admin @error('slug') border-red-500 @enderror" value="{{ old('slug') }}">
                        <p class="text-xs text-gray-500 dark:text-gray-400 mt-1">Оставьте пустым для автоматической генерации из названия</p>
                        @error('slug')
                            <p class="text-red-500 text-xs mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    <div>
                        <label for="description" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Описание</label>
                        <textarea name="description" id="description" rows="4" class="form-input-admin @error('description') border-red-500 @enderror">{{ old('description') }}</textarea>
                        @error('description')
                            <p class="text-red-500 text-xs mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    <div class="pt-4">
                        <button type="submit" class="btn-primary-admin">Сохранить категорию</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>
    // Автогенерация slug из названия
    document.getElementById('name').addEventListener('input', function() {
        const nameValue = this.value;
        const slugInput = document.getElementById('slug');
        
        // Только если поле slug пустое или не редактировалось вручную
        if (slugInput.value === '' || slugInput._autoGenerated) {
            slugInput.value = nameValue
                .toLowerCase()
                .replace(/[^\wа-яё\s]/gi, '')
                .replace(/\s+/g, '-');
            slugInput._autoGenerated = true;
        }
    });
    
    document.getElementById('slug').addEventListener('input', function() {
        // Если пользователь вручную отредактировал slug
        if (this.value !== '') {
            this._autoGenerated = false;
        }
    });
</script>
@endpush